# Generated by Django 3.1 on 2020-08-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=255)),
                ('request', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FileLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='chatfiles/%Y/%m/%d/')),
                ('owner', models.CharField(max_length=255)),
                ('room_id', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('room_id', models.CharField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=255)),
                ('request', models.CharField(max_length=255)),
                ('helping', models.BooleanField(default=False)),
            ],
        ),
    ]
