# Generated by Django 3.0.8 on 2020-08-01 18:22

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=255)),
                ('request', jsonfield.fields.JSONField()),
            ],
        ),
    ]
