# Generated by Django 3.0.8 on 2020-08-01 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resource',
            new_name='UserQueue',
        ),
    ]
