# Generated by Django 3.0.8 on 2020-08-01 18:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200801_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='userqueue',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userqueue',
            name='request',
            field=models.CharField(max_length=255),
        ),
    ]
