# Generated by Django 3.0.8 on 2020-08-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20200801_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='userqueue',
            name='helping',
            field=models.BooleanField(default=False),
        ),
    ]
