# Generated by Django 3.0.8 on 2020-08-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_userqueue_helping'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('room_id', models.CharField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=255)),
                ('request', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='userqueue',
            name='log_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
