# Generated by Django 3.0.8 on 2020-08-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20200822_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatlog',
            name='room_id',
        ),
        migrations.AddField(
            model_name='filelog',
            name='owner',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filelog',
            name='room_id',
            field=models.CharField(default=-1, max_length=255),
            preserve_default=False,
        ),
    ]
